# Generated by Django 6.0.4 on 2026-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_color_product',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(default='White', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('color_name', 'product'), name='unique_color_name_per_product'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
