# Generated by Django 6.0.4 on 2026-05-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_productvariant_unique_color_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(max_length=255),
        ),
    ]
