# Generated by Django 6.0.4 on 2026-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productvariant_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvariantimage',
            name='unique_product_variant_image',
        ),
        migrations.RemoveConstraint(
            model_name='productvariantimage',
            name='unique_product_variant_image_order',
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='productvariantimage',
            constraint=models.UniqueConstraint(fields=('product_variant', 'image_url'), name='unique_image_url_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariantimage',
            constraint=models.UniqueConstraint(fields=('product_variant', 'order'), name='unique_image_order_per_variant'),
        ),
    ]
