# Generated by Django 6.0.4 on 2026-05-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantsku',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
