# Generated by Django 6.0.4 on 2026-05-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_productvariantsku_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
