# Generated by Django 6.0.4 on 2026-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
