from enum import Enum
from typing import Generic, TypeVar
from datetime import datetime
from abc import ABC, abstractmethod


class ApiCode(Enum):
    # AUTH 
    AUTH_LOGIN_SUCCESS = "AUTH.LOGIN_SUCCESS"
    AUTH_INVALID_CREDENTIALS = "AUTH.INVALID_CREDENTIALS"
    AUTH_INVALID_TOKEN = "AUTH.INVALID_TOKEN"
    AUTH_EXPIRED_TOKEN = "AUTH.EXPIRED_TOKEN"
    AUTH_MISSING_TOKEN = "AUTH.MISSING_TOKEN"
    AUTH_USER_INACTIVE = "AUTH.USER_INACTIVE"
    AUTH_UNAUTHORIZED_ACTION = "AUTH.UNAUTHORIZED_ACTION"
    
    # ME API
    AUTH_SESSION_ACTIVE = "AUTH.SESSION_ACTIVE"
    
    
    # AUTH Signup
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH.EMAIL_ALREADY_EXISTS"
    AUTH_SIGNUP_SUCCESS = "AUTH.SIGNUP_SUCCESS"
    
    # VALIDATION
    VALIDATION_INVALID_EMAIL = "VALIDATION.INVALID_EMAIL"
    VALIDATION_WEAK_PASSWORD = "VALIDATION.WEAK_PASSWORD"

    # SYSTEM
    SYSTEM_INTERNAL_ERROR = "SYSTEM.INTERNAL_ERROR"
    SYSTEM_SERVICE_UNAVAILABLE = "SYSTEM.SERVICE_UNAVAILABLE"

    # REQUEST
    REQUEST_INVALID = "REQUEST.INVALID"
    REQUEST_CONFIRMATION_REQUIRED = "REQUEST.CONFIRMATION_REQUIRED"
    
    #USER
    USER_PROFILE_FETCHED = "USER.PROFILE_FETCHED"

    # FILTER
    FILTER_CREATED = "FILTER.CREATED"
    FILTER_NAME_ALREADY_EXISTS = "FILTER.NAME_ALREADY_EXISTS"
    FILTER_NOT_FOUND = "FILTER.NOT_FOUND"
    FILTER_HARD_DELETED = "FILTER.HARD_DELETED"
    FILTER_DEACTIVATED = "FILTER.DEACTIVATED"
    FILTER_ALREADY_INACTIVE = "FILTER.ALREADY_INACTIVE"
    FILTER_ACTIVATED = "FILTER.ACTIVATED"
    FILTER_ALREADY_ACTIVE = "FILTER.ALREADY_ACTIVE"
    FILTER_UPDATED = "FILTER.UPDATED"
    FILTERS_RETRIEVED = "FILTERS.RETRIEVED"
    FILTERS_SEARCH_RESULTS = "FILTERS.SEARCH_RESULTS"

    # CATEGORY
    CATEGORY_CREATED = "CATEGORY.CREATED"
    CATEGORY_NAME_ALREADY_EXISTS = "CATEGORY.NAME_ALREADY_EXISTS"
    CATEGORY_UPDATED = "CATEGORY.UPDATED"
    CATEGORY_NOT_FOUND = "CATEGORY.NOT_FOUND"
    CATEGORY_ALREADY_EXISTS = "CATEGORY.ALREADY_EXISTS"
    CATEGORY_ACTIVATED = "CATEGORY.ACTIVATED"
    CATEGORY_DEACTIVATED = "CATEGORY.DEACTIVATED"
    CATEGORY_ALREADY_ACTIVE = "CATEGORY.ALREADY_ACTIVE"
    CATEGORY_ALREADY_INACTIVE = "CATEGORY.ALREADY_INACTIVE"
    CATEGORY_INACTIVE = "CATEGORY.INACTIVE"
    CATEGORIES_RETRIEVED = "CATEGORIES.RETRIEVED"
    CATEGORIES_SELECT_RETRIEVED = "CATEGORIES.SELECT.RETRIEVED"
    CATEGORIES_FILTERS_RETRIEVED = "CATEGORIES.FILTERS.RETRIEVED"

    # CATEGORY FILTER
    CATEGORY_FILTER_ENABLED = "CATEGORY_FILTER.ENABLED"
    CATEGORY_FILTER_ALREADY_ENABLED = "CATEGORY_FILTER.ALREADY_ENABLED"
    CATEGORY_FILTER_REMOVED = "CATEGORY_FILTER.REMOVED"
    CATEGORY_FILTER_NOT_ASSOCIATED = "CATEGORY_FILTER.NOT_ASSOCIATED"
    
    # FILTER VALUE
    FILTER_VALUE_CREATED = "FILTER_VALUE.CREATED"
    FILTER_VALUE_UPDATED = "FILTER_VALUE.UPDATED"
    FILTER_VALUE_ALREADY_EXISTS = "FILTER_VALUE.ALREADY_EXISTS"
    FILTER_VALUE_NOT_FOUND = "FILTER_VALUE.NOT_FOUND"
    FILTER_VALUE_HARD_DELETED = "FILTER_VALUE.HARD_DELETED"
    FILTER_VALUE_DEACTIVATED = "FILTER_VALUE.DEACTIVATED"
    FILTER_VALUE_ALREADY_INACTIVE = "FILTER_VALUE.ALREADY_INACTIVE"
    FILTER_VALUE_ACTIVATED = "FILTER_VALUE.ACTIVATED"
    FILTER_VALUE_ALREADY_ACTIVE = "FILTER_VALUE.ALREADY_ACTIVE"
    # PRODUCT FILTER VALUE (assignments)
    PRODUCT_FILTER_VALUES_ASSIGNED = "PRODUCT_FILTER_VALUES.ASSIGNED"
    FILTER_VALUE_NOT_ALLOWED_FOR_CATEGORY = "FILTER_VALUE.NOT_ALLOWED_FOR_CATEGORY"

    # PRODUCT
    PRODUCT_CREATED = "PRODUCT.CREATED"
    PRODUCT_DUPLICATE_NAME = "PRODUCT.DUPLICATE_NAME"
    PRODUCT_NOT_FOUND = "PRODUCT.NOT_FOUND"

    # VARIANT
    VARIANT_CREATED = "VARIANT.CREATED"
    VARIANT_BULK_CREATED = "VARIANT.BULK_CREATED"
    VARIANT_DUPLICATE_COLOR_NAME_IN_PRODUCT = "VARIANT.DUPLICATE_COLOR_NAME_IN_PRODUCT"
    UNSUPPORTED_IMAGE_CONTENT_TYPE = "VARIANT.UNSUPPORTED_IMAGE_CONTENT_TYPE"

    # SKU
    SKU_CREATED = "SKU.CREATED"
    SKU_DUPLICATE_SIZE_IN_VARIANT = "SKU.DUPLICATE_SIZE_IN_VARIANT"

    # PRODUCT
    PRODUCT_ARCHIVED = "PRODUCT.ARCHIVED"

    # IMAGES
    IMAGES_UPLOADED = "IMAGES.UPLOADED"
    RESOURCE_NOT_FOUND = "RESOURCE.NOT_FOUND"
   


class BaseDTO(ABC):
    @abstractmethod
    def to_dict(self) -> dict:
        pass
T = TypeVar('T' , bound=BaseDTO)

class ApiResponse(Generic[T]):
    def __init__(
            self,
            code: ApiCode,
            message: str,
            status: int,
            data: T | None = None,
        ):
        self.data = data
        self.code = code
        self.message = message
        self.timestamp = datetime.now().isoformat()
        self.status = status  
        
    def to_dict(self) -> dict:
        result = {
            "timestamp": self.timestamp,
            "code": self.code.value,
            "message": self.message,
        }

        if self.data is not None:
            result["data"] = self.data.to_dict()

        return result
        
        