# Generated by Django 6.0.4 on 2026-04-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'filter',
            },
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filter', models.ForeignKey(db_column='filter_id', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='classification_app.filter')),
            ],
            options={
                'db_table': 'filter_value',
            },
        ),
        migrations.CreateModel(
            name='CategoryFilterValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='category_filter_values', to='classification_app.category')),
                ('filter_value', models.ForeignKey(db_column='filter_value_id', on_delete=django.db.models.deletion.CASCADE, related_name='filter_value_categories', to='classification_app.filtervalue')),
            ],
            options={
                'db_table': 'category_filter_value',
            },
        ),
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='category_filters', to='classification_app.category')),
                ('filter', models.ForeignKey(db_column='filter_id', on_delete=django.db.models.deletion.CASCADE, related_name='filter_categories', to='classification_app.filter')),
            ],
            options={
                'db_table': 'category_filter',
                'constraints': [models.UniqueConstraint(fields=('category', 'filter'), name='unique_category_filter')],
            },
        ),
        migrations.AddConstraint(
            model_name='filtervalue',
            constraint=models.UniqueConstraint(fields=('filter', 'name'), name='unique_filter_value_name'),
        ),
        migrations.AddConstraint(
            model_name='categoryfiltervalues',
            constraint=models.UniqueConstraint(fields=('category', 'filter_value'), name='unique_category_filter_value'),
        ),
    ]
