# Generated by Django 6.0.4 on 2026-04-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categoryfilter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categoryfiltervalues',
            table=None,
        ),
        migrations.AlterModelTable(
            name='filter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='filtervalue',
            table=None,
        ),
    ]
