# Generated by Django 6.0.4 on 2026-04-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0002_alter_category_table_alter_categoryfilter_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfiltervalues',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='allowed_filter_values', to='classification_app.category'),
        ),
    ]
