# Generated by Django 6.0.4 on 2026-04-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0003_alter_categoryfiltervalues_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
