# Generated by Django 6.0.4 on 2026-04-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0004_alter_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtervalue',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='slug',
            field=models.SlugField(),
        ),
    ]
