# Generated by Django 6.0.4 on 2026-04-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0005_filtervalue_description_alter_filtervalue_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filtervalue',
            name='unique_filter_value_name',
        ),
        migrations.AlterField(
            model_name='categoryfiltervalues',
            name='filter_value',
            field=models.ForeignKey(db_column='filter_value_id', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='classification_app.filtervalue'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='filtervalue',
            index=models.Index(fields=['filter_id'], name='filter_valu_filter__2c46aa_idx'),
        ),
        migrations.AddIndex(
            model_name='filtervalue',
            index=models.Index(fields=['slug'], name='filter_valu_slug_9e8514_idx'),
        ),
        migrations.AlterModelTable(
            name='filtervalue',
            table='filter_values',
        ),
    ]
