# Generated by Django 6.0.4 on 2026-04-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0006_remove_filtervalue_unique_filter_value_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='categoryfilter',
            table='category_filters',
        ),
        migrations.AlterModelTable(
            name='categoryfiltervalues',
            table='category_filter_values',
        ),
        migrations.AlterModelTable(
            name='filter',
            table='filters',
        ),
    ]
