# Generated by Django 6.0.4 on 2026-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0007_alter_category_table_alter_categoryfilter_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtervalue',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
