# Generated by Django 6.0.4 on 2026-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0008_alter_filtervalue_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoryfiltervalues',
            name='unique_category_filter_value',
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='filtervalue',
            options={'ordering': ['id']},
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'gender'), name='unique_category_name_gender'),
        ),
        migrations.DeleteModel(
            name='CategoryFilterValues',
        ),
    ]
