# Generated by Django 6.0.4 on 2026-04-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0009_remove_categoryfiltervalues_unique_category_filter_value_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_gender',
        ),
    ]
