# Generated by Django 6.0.4 on 2026-04-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_app', '0010_remove_category_unique_category_name_gender'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'gender'), name='unique_category_name_gender'),
        ),
    ]
